### ISSUE TITLE
Language classes have incorrect QuarterOffered info

### ISSUE THREAD

**Issue by joyzou1** [park-junha/PlanForGrad#66]
Some classes are not offered every quarter, depending on what level language AND what level language the user is planning to take (placement test, etc.). For example, elementary French 1 is only offered fall quarter, and elementary French 2 is offered only in the winter.

**Comment by park-junha** [comment]
Lines 813 and 821 on [this](https://github.com/park-junha/PlanForGrad/commit/0ad72e47cb14e5ef23baec4ef0d6c936f8f55714#diff-f9b29c689c5e48f19ac15c6b5c3687e1) commit
