### ISSUE TITLE
RTC2, RTC3, Adv Writing, Ethics, C&I3 need suggested class

### ISSUE THREAD

**Issue by park-junha** [park-junha/PlanForGrad#75]
All core requirements except the ones in the title have suggested classes. Originally from #73, see for more info

**Comment by joyzou1** [comment]
For an ethics course, I recommend ENGR19 Ethics in technology because it's one of the only ethics courses relevant to STEM majors.

**Comment by park-junha** [comment]
reopen later when this becomes more relevant
