### ISSUE TITLE
Web GUI Changes

### ISSUE THREAD

**Issue by DhanushAShetty** [park-junha/PlanForGrad#83]
to Accommodate All Majors: 
- Need one page that asks what’s the major and then the next page should give the major+ minor classes checklist based off of that major (this is SIO easy to pick classes for the student) 

Aesthetic: 
- Please please change the color of the link on the first page (blue link) 
- Change course availing link to specific link of the page with Degree Audit 
- Increase size of the “schedule” Button

**Comment by park-junha** [comment]
Need mockup from @DhanushAShetty and Jocelyn.

**Comment by park-junha** [comment]
@Hanzhuo-Gong construction zone needs to be moved to the bottom right corner

suggested by @DhanushAShetty

**Comment by Hanzhuo-Gong** [comment]
Can't move to bottom due to an image on the bottom
